# Generated by Django 5.1.3 on 2025-01-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0002_remove_qrcodes_multiple_remove_qrcodes_parmanantqr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodes',
            name='multiple_base64',
        ),
        migrations.RemoveField(
            model_name='qrcodes',
            name='parmanantqr_base64',
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='multiple',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='parmanantqr',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
